### ISSUE TITLE
Find new location for example.conf links

### ISSUE THREAD

**Issue by kapunahelewong** [trickstercache/trickstercache.org#5]
Currently, the following files refer to `'../cmd/trickster/conf/example.conf'`, however, it has moved or changed.

collapsed-forwarding.md
configuring.md
health.md
multi-origin.md
negative-caching.md
new-changed-1.1.md
retention.md

Per this [comment](https://github.com/trickstercache/trickstercache.org/issues/3#issuecomment-862502353) in #3, the links originally went here: `../cmd/trickster/conf/example.conf`. It appears that the original file might have moved/changed because there's no more `conf` directory in https://github.com/trickstercache/trickster/tree/main/cmd/trickster.

**Comment by jranson** [comment]
Example configs are now located in the [examples directory](https://github.com/trickstercache/trickster/tree/main/examples/conf). Let me know if that helps!

**Comment by jranson** [comment]
Btw, it looks like the docs that have been pulled over are outdated, which makes sense because Nathaniel's fork is from 2020. That is why many of the links like this are broken. If you want to grab the current markdown from the main project ([here](https://github.com/trickstercache/trickster/tree/main/docs)), most of the broken things will be fixed.

**Comment by kapunahelewong** [comment]
Thank you for the links! I've incorporated all the most recent info now.
